#!/usr/bin/env bash
# bootstrap.sh — interactive first-time contributor setup.
# Writes Config/Local.xcconfig (signing override), installs toolchain deps, and
# regenerates the Xcode project. Free Apple IDs work with limitations — see
# docs/codesigning.md. PLAN.md §12.3.
#
# Usage: ./scripts/bootstrap.sh [--open]
#   --open   open CleanShare.xcodeproj in Xcode when finished.
set -euo pipefail

cd "$(dirname "$0")/.."

OPEN_XCODE=false
for arg in "$@"; do
  case "$arg" in
    --open) OPEN_XCODE=true ;;
    *) echo "Unknown argument: $arg" >&2; exit 2 ;;
  esac
done

LOCAL_XCCONFIG="Config/Local.xcconfig"

# 1. Guard against clobbering an existing config.
if [ -f "$LOCAL_XCCONFIG" ]; then
  read -rp "$LOCAL_XCCONFIG already exists. Overwrite? [y/N] " overwrite
  case "$overwrite" in
    [yY] | [yY][eE][sS]) ;;
    *) echo "Keeping existing $LOCAL_XCCONFIG. Aborting." >&2; exit 0 ;;
  esac
fi

# 2. DEVELOPMENT_TEAM_OVERRIDE — exactly 10 alphanumeric chars (Apple Team ID shape).
DEVELOPMENT_TEAM_OVERRIDE=""
while true; do
  read -rp "Apple Development Team ID (10 alphanumeric chars): " DEVELOPMENT_TEAM_OVERRIDE
  if printf '%s' "$DEVELOPMENT_TEAM_OVERRIDE" | grep -Eq '^[A-Za-z0-9]{10}$'; then
    break
  fi
  echo "  Invalid: must be exactly 10 alphanumeric characters (e.g. ABCDE12345)." >&2
done

# 3. BUNDLE_PREFIX — reverse-DNS shaped; default dev.local.
BUNDLE_PREFIX=""
while true; do
  read -rp "Bundle prefix (reverse-DNS) [dev.local]: " BUNDLE_PREFIX
  BUNDLE_PREFIX="${BUNDLE_PREFIX:-dev.local}"
  if printf '%s' "$BUNDLE_PREFIX" | grep -Eq '^[A-Za-z][A-Za-z0-9]*(\.[A-Za-z][A-Za-z0-9-]*)+$'; then
    break
  fi
  echo "  Invalid: must be reverse-DNS shaped (e.g. dev.local or com.example)." >&2
done

# 4. Write Config/Local.xcconfig.
{
  echo "// Generated by scripts/bootstrap.sh. Local.xcconfig is gitignored."
  echo "DEVELOPMENT_TEAM_OVERRIDE = ${DEVELOPMENT_TEAM_OVERRIDE}"
  echo "BUNDLE_PREFIX = ${BUNDLE_PREFIX}"
} > "$LOCAL_XCCONFIG"
echo "Wrote $LOCAL_XCCONFIG."

# 5. Homebrew dependencies.
if [ -f Brewfile ]; then
  if command -v brew >/dev/null 2>&1; then
    echo "Running brew bundle..."
    brew bundle
  else
    echo "brew not found on PATH; skipping brew bundle. See CLAUDE.md for setup." >&2
  fi
fi

# 6. Ruby gems (Fastlane etc.).
if [ -f Gemfile ]; then
  if command -v bundle >/dev/null 2>&1; then
    echo "Running bundle install..."
    bundle install --path vendor/bundle
  else
    echo "bundle not found on PATH; skipping gem install. See CLAUDE.md for setup." >&2
  fi
fi

# 7. Generate the Xcode project.
echo "Generating Xcode project..."
./scripts/generate-project.sh

# 8. Optionally open Xcode.
if [ "$OPEN_XCODE" = true ]; then
  open CleanShare.xcodeproj
fi

echo "Bootstrap complete."
