@testable import CleanShareCore
import XCTest

/// Wall-clock performance coverage for the engine on large synthetic media.
/// Baselines are deliberately generous — GitHub-hosted CI runners clean a 12 MP
/// HEIC in ~0.8 s where a dev machine takes ~0.05 s, so these thresholds absorb
/// that variance and only catch order-of-magnitude regressions, not millisecond
/// drift. Fixtures are generated by `scripts/make-perf-fixtures.sh`. See PLAN.md §5.2, §8.
final class PerformanceTests: XCTestCase {
    private func fixtureURL(_ name: String, _ ext: String) throws -> URL {
        try XCTUnwrap(
            Bundle.module.url(forResource: name, withExtension: ext, subdirectory: "PerfFixtures"),
            "missing perf fixture \(name).\(ext) — run scripts/make-perf-fixtures.sh"
        )
    }

    /// Runs an async closure to completion from a synchronous test body.
    private func runBlocking(timeout: TimeInterval, _ work: @escaping @Sendable () async throws -> Void) {
        let done = expectation(description: "async perf work")
        Task {
            do { try await work() } catch { XCTFail("perf work threw: \(error)") }
            done.fulfill()
        }
        wait(for: [done], timeout: timeout)
    }

    private static func cleanImage(_ input: URL) async throws {
        let output = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
            .appendingPathExtension(input.pathExtension)
        defer { try? FileManager.default.removeItem(at: output) }
        _ = try await ImageIOCleaner().clean(input: input, output: output, prefs: CleaningPreferences())
    }

    private static func cleanVideo(_ input: URL) async throws {
        let output = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
            .appendingPathExtension(input.pathExtension)
        defer { try? FileManager.default.removeItem(at: output) }
        _ = try await AVPassthroughCleaner().clean(input: input, output: output, prefs: CleaningPreferences())
    }

    /// Times a single async run and asserts it stays under `baseline` seconds.
    private func assertUnder(_ baseline: TimeInterval, _ work: @escaping @Sendable () async throws -> Void) {
        let start = Date()
        self.runBlocking(timeout: baseline * 4 + 5, work)
        let elapsed = Date().timeIntervalSince(start)
        XCTAssertLessThan(elapsed, baseline, "took \(elapsed)s, baseline \(baseline)s")
    }

    func testPerfJPEG12MP() throws {
        let input = try fixtureURL("jpeg_12mp", "jpg")
        measure { self.runBlocking(timeout: 30) { try await Self.cleanImage(input) } }
        self.assertUnder(2.0) { try await Self.cleanImage(input) }
    }

    func testPerfHEIC12MP() throws {
        let input = try fixtureURL("heic_12mp", "heic")
        measure { self.runBlocking(timeout: 30) { try await Self.cleanImage(input) } }
        self.assertUnder(2.5) { try await Self.cleanImage(input) }
    }

    func testPerf4KH264() throws {
        let input = try fixtureURL("h264_4k_10s", "mp4")
        measure { self.runBlocking(timeout: 60) { try await Self.cleanVideo(input) } }
        self.assertUnder(15.0) { try await Self.cleanVideo(input) }
    }
}
